apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "loki-rule-operator.labels" . | nindent 4 }}
  name: {{ include "loki-rule-operator.fullname" . }}-viewer-role
rules:
- apiGroups:
  - quero.com
  resources:
  - lokirules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quero.com
  resources:
  - lokirules/status
  verbs:
  - get