{{- $locals := include "loki-rule-operator.locals" . | fromYaml }}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $locals.commonResources.serviceAccount.name }}
  labels:
    {{- include "loki-rule-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
