# permissions for end users to view lokiRules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lokiRule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operators
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
  name: lokiRule-viewer-role
rules:
- apiGroups:
  - quero.com
  resources:
  - lokiRules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quero.com
  resources:
  - lokiRules/status
  verbs:
  - get
