---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - quero.com
  resources:
  - lokiRules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quero.com
  resources:
  - lokiRules/finalizers
  verbs:
  - update
- apiGroups:
  - quero.com
  resources:
  - lokiRules/status
  verbs:
  - get
  - patch
  - update
