image:
  repository: "ghcr.io/quero-edu/loki-rule-operator"
  pullPolicy: IfNotPresent
  tag: "0.6.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

resources:
  limits:
    cpu: 200m
    memory: 254Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

lokiRuleOperator:
  lokiLabelSelector: "app.kubernetes.io/name=loki"
  lokiNamespace: ""
  lokiRuleMountPath: "/etc/loki/rules"
  logLevel: info
  metrics:
    port: 8080
  healthProbe:
    port: 8081
  leaderElection:
    enabled: true
    id: loki-rule-operator.quero.com
  lokiURL: ""
  # Extra HTTP headers specified as HeaderName=Value which will be passed on to Loki
  lokiHeaders: []
  onlyReconcileRules: false
keepCrds: false
