apiVersion: quero.com/v1alpha1
kind: LokiRule
metadata:
  labels:
    app.kubernetes.io/name: lokirule-2
    app.kubernetes.io/instance: lokirule-sample
    app.kubernetes.io/component: lokirule
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operators
  name: lokirule-sample-2
spec:
  groups:
    - name: my-rule-group
      rules:
        - alert: HighRequestLatency
          expr: rate({job="myjob"} |~ "request"[5m]) > 0.6
          for: 10m
          labels:
            severity: page
          annotations:
            summary: High request latency
