name: Go test

on: [push]

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test GO
        run: make test

  helm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Lint Helm
        run: make lint
      - name: Test Helm
        run: make helm-test
