name: Go test

on: [pull_request]

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: -c .golangci.yml 
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Test GO
        run: make test

  helm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Lint Helm
        run: make helm-lint
      - name: Test Helm
        run: make helm-test
